'use strict';
(() => {
const DUCK_COUNT = 5;
const elements = Object.fromEntries(Array.from(document.querySelectorAll('[id]'), el => [el.id, el]));

const images=["./assets/memory-1.webp", "./assets/memory-2.webp", "./assets/memory-3.webp", "./assets/memory-4.webp"];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,scene=document.querySelector('.scene'),duckBox=elements['ducks'],modal=elements['photo'],status=elements['status'],nextButton=elements['next'];
const colors=['#ffe070','#ffe789','#ffdb63','#ffea9e','#ffdc76'];
function duckSvg(color){return `<svg viewBox="0 0 32 30" shape-rendering="crispEdges" aria-hidden="true"><path fill="#bf8b38" d="M10 25h6v3h-6zm10 0h6v3h-6z"/><path fill="${color}" d="M18 2h8v2h3v12h-4v8h-4v3H8v-3H4v-4H1v-8h4v4h10V7h3z"/><path fill="#fff2ad" d="M18 4h7v3h-7zm-12 14h7v4H6z"/><path fill="#f5b93f" d="M10 19h8v3h-8z"/><path fill="#f29349" d="M26 10h6v5h-6z"/><path fill="#3f4944" d="M23 7h3v3h-3z"/><path fill="#f6a0a6" d="M21 12h3v2h-3z"/></svg>`;}
const ducks=Array.from({length:DUCK_COUNT},(_,i)=>{let b=document.createElement('button');b.className='duck';b.style.setProperty('--left',(5+i*18)+'%');b.style.setProperty('--swim',(10+i*16)+'%');b.style.setProperty('--delay',(-i*.3)+'s');b.innerHTML=duckSvg(colors[i])+`<span>${i+1}</span>`;b.setAttribute('aria-label','Duck '+(i+1)+' — jump in and reveal a memory');b.onclick=()=>{startSound();if(i===index)jump();else if(i<index&&!busy)showPhoto(i);};duckBox.appendChild(b);return b;});
let index=0,busy=false,jumpTimer,photoTimer,autoTimer;
function controls(){ducks.forEach((b,i)=>b.disabled=busy||i>index);nextButton.disabled=busy||index===DUCK_COUNT;nextButton.textContent=index===DUCK_COUNT?'ALL FIVE DUCKS ARE SWIMMING!':'DUCK '+(index+1)+' · JUMP IN! →';}
function closePhoto(){if(typeof modal.close==='function')modal.close();else{modal.removeAttribute('open');nextButton.focus();}}
modal.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();closePhoto();}if(event.key==='Tab'){const first=elements['close'],last=elements['continue'];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});
function showPhoto(i){elements['counter'].textContent='SPLASH '+(i+1)+' OF 5';elements['photo-title'].textContent=['Hello, little sunshine!','A tiny bundle of joy!','Adventure looks good on you!','Sweet little giggles!','So many reasons to smile!'][i];const box=elements['photos'];box.replaceChildren();box.className='photos'+(i===4?' gallery':'');(i===4?images:[images[i]]).forEach((src,j)=>{let img=new Image();img.decoding='async';img.className='memory-image';const loading=document.createElement('p');loading.className='image-loading';loading.textContent='Loading memory…';box.appendChild(loading);img.onload=()=>loading.remove();img.onerror=()=>{img.remove();loading.textContent='This memory could not load. You can still continue to the next duck.';};img.src=src;img.alt='Samara Shyle — happy memory '+(i===4?j+1:i+1);box.appendChild(img);});elements['caption'].textContent=i===4?'All four little memories, together. Quack, quack, hooray!':'A little memory from Samara Shyle’s pond.';elements['continue'].textContent=index===DUCK_COUNT?'BACK TO OUR HAPPY POND':'NEXT LITTLE DUCK →';if(!modal.open){if(typeof modal.showModal==='function')modal.showModal();else modal.setAttribute('open','');}elements['close'].focus();}
function splash(i){splashSound();const x=17+i*16;for(let n=0;n<12&&!reduced;n++){let d=document.createElement('i');d.className='splash';d.style.setProperty('--x',x+'%');d.style.setProperty('--dx',(Math.random()-.5)*140+'px');d.style.setProperty('--dy',(-30-Math.random()*90)+'px');scene.appendChild(d);setTimeout(()=>d.remove(),900);}let r=document.createElement('i');r.className='ripple';r.style.setProperty('--x',(x-4)+'%');scene.appendChild(r);setTimeout(()=>r.remove(),1000);}
function jump(){if(busy||index>=DUCK_COUNT||modal.open)return;clearTimeout(autoTimer);busy=true;controls();const i=index;status.textContent='Duck '+(i+1)+' says… here I come!';ducks[i].classList.add('jumping');ducks[i].style.top='64%';ducks[i].style.left=(10+i*16)+'%';jumpTimer=setTimeout(()=>{ducks[i].classList.remove('jumping');ducks[i].classList.add('swimming');splash(i);index++;status.textContent=index+' of 5 little ducks in the pond!';photoTimer=setTimeout(()=>{busy=false;controls();showPhoto(i);},reduced?50:450);},reduced?50:950);}
nextButton.onclick=()=>{startSound();jump();};elements['continue'].onclick=()=>{closePhoto();if(index<DUCK_COUNT)jump();};elements['close'].onclick=()=>closePhoto();modal.addEventListener('close',()=>{nextButton.focus();});elements['replay'].onclick=()=>{clearTimeout(autoTimer);clearTimeout(jumpTimer);clearTimeout(photoTimer);index=0;busy=false;ducks.forEach(b=>{b.className='duck';b.style.top='';b.style.left='';});status.textContent='Five little ducks, ready for another adventure!';controls();startSound();};controls();status.textContent="Five little ducks are ready. Choose Duck 1 or Jump In to begin.";
// Soft, original synthesized music and splash effects. No external audio files.
let enabled=false,ac,master,musicTimer,note=0,nextTime=0;const soundButton=elements['sound'];
function soundLabel(){let playing=Boolean(enabled&&ac?.state==='running');soundButton.setAttribute('aria-label',playing?'Turn sound off':'Turn sound on');soundButton.textContent=playing?'♫ SOUND: ON':enabled?'♫ TAP FOR SOUND':'♫ SOUND: OFF';soundButton.setAttribute('aria-pressed',String(playing));elements['sound-note'].textContent=enabled&&!playing?'Tap anywhere to wake up the music!':'A happy little tune and splishy-splashy sounds.';}
function tone(midi,t,d,g){let o=ac.createOscillator(),e=ac.createGain();o.type='triangle';o.frequency.value=440*2**((midi-69)/12);e.gain.setValueAtTime(0,t);e.gain.linearRampToValueAtTime(g,t+.015);e.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(e);e.connect(master);o.start(t);o.stop(t+d+.02);o.onended=()=>{o.disconnect();e.disconnect();};}
function schedule(){if(!enabled||ac.state!=='running')return;const melody=[72,76,79,76,77,81,79,0,74,77,81,77,76,74,72,0];if(nextTime<ac.currentTime)nextTime=ac.currentTime+.04;while(nextTime<ac.currentTime+.15){let m=melody[note%16];if(m)tone(m,nextTime,.26,modal.open ? .07 : .13);if(note%4===0)tone([48,53,50,55][Math.floor(note%16/4)],nextTime,.5,.05);note++;nextTime+=.34;}}
async function startSound(){if(!enabled)return;try{if(!ac){ac=new(window.AudioContext||window.webkitAudioContext)();master=ac.createGain();master.gain.value=.35;master.connect(ac.destination);}soundLabel();await ac.resume();if(!enabled){ac.suspend();return;}clearInterval(musicTimer);nextTime=ac.currentTime+.04;schedule();musicTimer=setInterval(schedule,90);soundLabel();}catch{enabled=false;clearInterval(musicTimer);soundLabel();elements['sound-note'].textContent='Sound is unavailable in this browser. You can still enjoy the pond.';}}
function splashSound(){if(!enabled||ac?.state!=='running')return;const t=ac.currentTime,b=ac.createBuffer(1,ac.sampleRate*.45,ac.sampleRate),data=b.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);let src=ac.createBufferSource(),filter=ac.createBiquadFilter(),gain=ac.createGain();src.buffer=b;filter.type='lowpass';filter.frequency.setValueAtTime(3500,t);filter.frequency.exponentialRampToValueAtTime(350,t+.4);gain.gain.setValueAtTime(.5,t);gain.gain.exponentialRampToValueAtTime(.001,t+.45);src.connect(filter);filter.connect(gain);gain.connect(master);src.start();src.onended=()=>{src.disconnect();filter.disconnect();gain.disconnect();};[76,81,88].forEach((n,i)=>tone(n,t+.12+i*.07,.18,.1));}
soundButton.onclick=()=>{if(enabled&&ac?.state==='running'){enabled=false;clearInterval(musicTimer);ac.suspend();}else{enabled=true;startSound();}soundLabel();};document.addEventListener('pointerdown',e=>{if(e.target.closest('#sound'))return;if(enabled&&ac?.state!=='running')startSound();});document.addEventListener('keydown',e=>{if(e.target===soundButton)return;if(enabled&&ac?.state!=='running')startSound();});soundLabel();
const canvas=elements['pond'],ctx=canvas.getContext('2d');canvas.width=480;canvas.height=225;let frame=0;
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}function cloud(x,y){rect(x,y,40,9,'#fffde9');rect(x+8,y-7,25,10,'#fffde9');rect(x+15,y-12,13,10,'#fffde9');}
function draw(){rect(0,0,480,225,'#cceef0');cloud((frame*.025)%560-40,40);cloud(300+(frame*.015)%240,22);rect(402,20,27,27,'#ffe17d');rect(410,29,3,4,'#b79345');rect(421,29,3,4,'#b79345');rect(414,38,7,2,'#b79345');rect(0,86,480,139,'#a8d48d');rect(0,100,480,12,'#95c781');for(let i=0;i<20;i++){let x=(i*61)%480;rect(x,113+(i%3)*7,3,6,'#6fa469');}ctx.fillStyle='#79b681';ctx.beginPath();ctx.ellipse(240,179,212,57,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#79cbd8';ctx.beginPath();ctx.ellipse(240,172,206,53,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#99e0e4';ctx.beginPath();ctx.ellipse(240,165,185,37,0,0,Math.PI*2);ctx.fill();for(let i=0;i<12;i++){let x=80+(i*43)%310;rect(x+Math.sin(frame*.015+i)*5,148+(i*17)%44,13,2,'#cef4e9');}for(const [x,y]of [[65,190],[370,167],[315,205]]){rect(x,y,18,5,'#6aa974');rect(x+4,y-3,10,9,'#6aa974');rect(x+7,y-5,5,4,'#f6bbd1');}for(let i=0;i<9;i++){let x=(i*73+13)%480,y=207+(i%2)*10;rect(x,y,2,9,'#5d985d');rect(x-3,y-4,8,6,i%2?'#fff4bc':'#f6bfd0');rect(x,y-2,2,2,'#e5b757');}rect(14,133,4,32,'#598755');rect(9,126,5,17,'#81754d');rect(452,127,4,31,'#598755');rect(448,119,5,17,'#81754d');frame++;if(!reduced&&!document.hidden)requestAnimationFrame(draw);}if(ctx)draw();
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&ctx&&!reduced)draw();if(document.hidden&&ac){ac.suspend();clearInterval(musicTimer);}else if(enabled&&ac)startSound();});

})();
